In [ ]:
#ПРЕДВАРИТЕЛЬНАЯ ОБРАБОТКА ДАННЫХ
import imp
import numpy as np
from sklearn import preprocessing
Input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                      [0.5, -7.9, 5.6],
                      [5.9, 2.3, -5.8]])
                     
data_binarized = preprocessing.Binarizer(threshold = 0.5).transform(Input_data)
print("\nBinarized data:\n", data_binarized)




Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [1]:
print("Mean = ", Input_data.mean(axis = 0))
print("Std deviation = ", Input_data.std(axis = 0))

NameError: ignored

In [ ]:
data_scaled = preprocessing.scale(Input_data)
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis = 0))

Mean = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Std deviation = [1. 1. 1.]


In [ ]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(Input_data)
print ("\nMin max scaled data:\n", data_scaled_minmax)



Min max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [ ]:
data_normalized_l1= preprocessing.normalize(Input_data, norm='l1')
print("nL1 normalized data:\n", data_normalized_l1)


nL1 normalized data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


In [ ]:
data_normalized_l2= preprocessing.normalize(Input_data, norm='l2') 
print("nL2 normalized data:\n", data_normalized_l2)


nL2 normalized data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


In [2]:
#ОПРЕДЕЛЕНИЕ ОБРАЗЦОВ МЕТОК
import numpy as np
from sklearn import preprocessing
input_labels=['red','black','red','green','black','yellow','white']

In [ ]:
encoder= preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

In [ ]:
test_labels=['green','red','black']
encoded_values= encoder.transform(test_labels)
print("\nLabels=", test_labels)


Labels= ['green', 'red', 'black']


In [ ]:
print("Encoded values=", list(encoded_values))


Encoded values= [1, 2, 0]


In [ ]:
encoded_values=[3,0,4,1]
decoded_list=encoder.inverse_transform(encoded_values)
print("\nDecoded labels =", list(decoded_list))             


Decoded labels = ['white', 'black', 'yellow', 'green']


In [ ]:
#ЛИНЕЙНЫЙ РЕГРЕССОР
import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
import matplotlib.pyplot as plt


In [ ]:
input = 'D:/ProgramData/linear.txt' #Теперь нам нужно предоставить входные данные, и мы сохранили наши данные в файле с
#именем linear.txt.
input_data = np.loadtxt(input, delimiter=',')#Нам нужно загрузить эти данные с помощью функции np.loadtxt .
X, y = input_data[:, :-1], input_data[:, -1]
training_samples = int(0.6 * len(X))
testing_samples = len(X) - num_training
X_train, y_train = X[:training_samples], y[:training_samples]
X_test, y_test = X[training_samples:], y[training_samples:]


In [ ]:
reg_linear = linear_model.LinearRegression()
reg_linear.fit(X_train, y_train)

In [ ]:
y_test_pred = reg_linear.predict(X_test)

In [ ]:
plt.scatter(X_test, y_test, color = 'indigo')
plt.plot(X_test, y_test_pred, color = 'yellowgreen', linewidth = 2)
plt.xticks(())
plt.yticks(())
plt.show()

In [ ]:
print("Performance of Linear regressor:")
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_test_pred), 2))
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_test_pred), 2))
print("Median abs error =", round(sm.median_absolute_error(y_test, y_test_pred), 2))
print("Explain var scr =", round(sm.explained_variance_score(y_test, y_test_pred),2))
print("R2 score =", round(sm.r2_score(y_test, y_test_pred), 2))

In [ ]:
input = 'D:/ProgramData/Mul_linear.txt'# нужно предоставить входные данные, и мы сохранили наши данные в файле с
#именем linear.txt.
input_data = np.loadtxt(input, delimiter=',')
X, y = input_data[:, :-1], input_data[:, -1]
training_samples = int(0.6 * len(X))
testing_samples = len(X) - num_training
X_train, y_train = X[:training_samples], y[:training_samples]
X_test, y_test = X[training_samples:], y[training_samples:]


In [ ]:
reg_linear_mul = linear_model.LinearRegression()
reg_linear_mul.fit(X_train, y_train)


In [ ]:
y_test_pred = reg_linear_mul.predict(X_test)
print("Performance of Linear regressor:")
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_test_pred), 2))
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_test_pred), 2))
print("Median abs error =", round(sm.median_absolute_error(y_test, y_test_pred), 2))
print("Explain var scr=", round(sm.explained_variance_score(y_test, y_test_pred), 2))
print("R2 score =", round(sm.r2_score(y_test, y_test_pred), 2))


In [ ]:
polynomial = PolynomialFeatures(degree = 10)
X_train_transformed = polynomial.fit_transform(X_train)
datapoint = [[2.23, 1.35, 1.12]]
poly_datapoint = polynomial.fit_transform(datapoint)
poly_linear_model = linear_model.LinearRegression()
poly_linear_model.fit(X_train_transformed, y_train)
print("\nLinear regression:\n", reg_linear_mul.predict(datapoint))
print("\nPolynomial regression:\n", poly_linear_model.predict(poly_datapoint))